// Synced from https://github.com/curiosus-dev/dotnet-tools, do not edit in place.
// Order and group labels come from sidebar_position front matter and _category_.json files in docs/.
export default { docs: [{ type: 'autogenerated', dirName: '.' }] };
